language: node_js
sudo: false
node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn product

before_deploy:
  - yarn product

deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    email: qowera@qq.com
    api_key:
      secure: OxgD+KMdKqBerzyNwTWeU/JMdQwE49fXAaL5gv+sO8aDceigVdk2djpBq20WQcBIEMPi/D54XJJgqaLDQOjpP7tzPEWGSUPdHESR0dsDEuPElnYZPil+O6v+6QKdtph0xKOJJKqQ2EJZQGOPOpYx5B5lItWBYa8CElF70kVF0FDrqj5JBhbQDZRVH7T/MC3gcimp7B/30ODwzrKJaRwPWRPn5V9dHxn9TVMRqmcxA4BXOn94Y7SWLf641i7CSq6fKc9xWk+oOiY2Tu0Fk4ll6NK9JthYbz16h7QD851EQiBgBO2DmG8nZXwxWrcsYLxSWCr9Z5txvyU2JA0iTCBUTElq3sU83JpBlsB7dTpy7iJlEwKFrEJ+iNPyYIpUfBFN1Kyj+N4WroGBC4uJsfYgYKar6QzFoOQy2qJp8wJaaoMkWaNyxjNlbf/ypi7Ecya7D8oDUDZHwehPvmpudQUULrVy8LVNWdtN54c59ewMyeD8fcLlKuBH82HzVCUBpVVPVOB2lT4seq7WdHN5U96X/ZsyllBrTWYaQBz7QkGoG9syGc/iWMWv3tMwEFnP6TMVy3GZxwaFlO2mjcOv/o0WJqfiiSrybeapyCgKS38dLls9k+Yv82gjZWMh3szg0cYHQnlP2Nbj6m7ul4hfjRMOJV6/K1/s8crySnVLk3IoO/E=
