language: node_js
sudo: false
node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn product

before_deploy:
  - yarn product

deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    email: qowera@qq.com
    api_key:
      secure: dccizonq5eqtdaG/Aw54YWb7EQj3V8kZnKGGPo/No9Mxd1LeXHiLhGC/gsTdO89+Fqpp+ET1H640Bc58BX9tFbMTcw3r7bHyK95J//GNVmDB36VMK8UYn0QBYlhAkl8mCMQhh0ZMgs7S6kNdeRtWqliW2TCEeLmktZ8qfip1xox8P+elsXGZAUmJs0v7Eegqbom8aboTRz1Kgdn5hFpIvUsVk7DQq7VIJ0RdffXpJQMT5q8wifK9iKlM/6/uChiSka4XEwUppSMlBfUx181tNrqAwIG0zdsZRDaic2aBTlt6KUMG/GG8QrE1p0xCiLprDUYs/2QKDaxREXFTl5ZwhjKnzRckIxK+v+0hzwg2riJKfYK6sUEoPnXEvHPmy+d5CkCnXuL3koRomQ2KDY1eSuUse/MB8oVTQA6x8131zDojxnYNwbde4IJkwbYry3KT4oyElDIuIObKSItmzJUaHKMZsw78xE3a4DXoQXkhm2eyxGRX6g0Yr8gVfI8jmt3NxLnlGMNKhpJ1bmUNB9D/pT0RTmrHplFRXjHzX0waqkZfPQVTmGWU2Fj8QrwT3PaEQF8iHPNuPVuND2V4V0vI9GzoMmlU5wGin8K58PmakiyEXrZnfe1kUK0cDYzgivNTLry+XAEEzj6SgHqPc6MEtD8iLb1+CVQ8AhbfXq1mB8w=
