language: node_js
sudo: false
node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn product

before_deploy:
  - yarn product

deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    email: qowera@qq.com
    api_key:
      secure: Ut0J0wXpjvQy+lGXh78HrAo8HIy3MJ/eN1LFBJOUzXtgpITNdR/NP5xtBDoahes3ioVJs5SGwqDmfMPnvpclgKBaJsj1AI37BTXdajuCWKp1nYvzvafv7Iv81KmuSg0wWSZ06LBBVyeLlXUO4y0/fa8J/QfMmvOTC85l0g/UXGaPIhIqyT8Ykrt5wdJQGVb+Zn8wQrNYI0lyyLtmo99Jr8Z32vMNz1WejArFaKMbyToneg0XEkkksggh/EWGLkijy+9E/FosmViddbRBrCe2qlMNmZlHH0kWCh6fMp8zhvtLwbquCJqXIHY+JzqdqTVNxFa+VFtzRBNIDpZcNysGEu8W/doCDM8oJZcKv0cYFPlAS6C4NYNFcBj9ioDVSQoHGhzPTjggDvjCWwMgykjwIY4pjKbVvha/SfQuFFi1VreKz9avlCE3maW9gaw+Zl07IooB0dCBoVqeaI+zjI/a6LIIKs1mhoh6e/NWqVhvco7mjzR4JS7y8ZwiI/Pj/m1o647kWnI/a6UIx+yZg9hJogSjpDIyThxujoBOMgrfKMU46CmE5YGz57tx0hg3xoUHuZ+HcArv0sy2PdfFJm3dArK7DAB8AS1DkZAb9oQjznERz2uP4bvHieF/rDPV79X/OAvmWU6hhxQK485HQuztEAYedTZLcbdfxmuihEuT/7s=
